id: opecha:P000483
initial_creation_type: ocr
source_metadata:
  id: bdr:W23438
  title: ཀུན་མཁྱེན་པད་དཀར་གྱི་བླ་སྒྲུབ་ཡེ་ཤེས་མཆོག་སྟེར
  volume:
    a681b7f440ab4c7782eb54cf92358bdd:
      image_group_id: I1937
      title: ''
      volume_number: 1
      total_pages: 94
  author: ''
ebook_metadata:
  title: ཀུན་མཁྱེན་པད་དཀར་གྱི་བླ་སྒྲུབ་ཡེ་ཤེས་མཆོག་སྟེར
  author: ''
  sku: P000483
  cover: cover.jpg
  layers:
  - pagination
