id: P000483
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W23438
  title: ཀུན་མཁྱེན་པད་དཀར་གྱི་བླ་སྒྲུབ་ཡེ་ཤེས་མཆོག་སྟེར
  author: ''
  volumes:
    a681b7f440ab4c7782eb54cf92358bdd:
      image_group_id: I1937
      title: ''
      volume_number: 1
      total_pages: 94
      base_file: v001.txt
